### ISSUE TITLE
Can't connect?

### ISSUE THREAD

**Issue by Advil-Robin** [ttn-zh/gateway-remote-config#109] opened 2017-04-06 13:23 UTC
Hi,
I'm getting the error `[main] failed to start the concentrator`

This is the full sys log:

```
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Ghoststream data is disabled
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Radiostream data is enabled
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Statusstream data is enabled
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Beacon is disabled
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Monitor is disabled
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Contact email configured to "lora@rallypodium.be"
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Description configured to "TTN Belgium - private"
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: Successfully contacted server router.eu.thethings.network
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: INFO: [main] Starting the concentrator
Apr  6 15:19:26 raspirobin ttn-gateway[14049]: ERROR: [main] failed to start the concentrator
Apr  6 15:19:28 raspirobin kernel: [ 1979.455992] w1_master_driver w1_bus_master1: Family 0 for 00.240000000000.42 is not registered.
Apr  6 15:19:31 raspirobin systemd[1]: ttn-gateway.service holdoff time over, scheduling restart.
Apr  6 15:19:31 raspirobin systemd[1]: Stopping The Things Network Gateway...
Apr  6 15:19:31 raspirobin systemd[1]: Starting The Things Network Gateway...
Apr  6 15:19:31 raspirobin systemd[1]: Started The Things Network Gateway.
Apr  6 15:19:32 raspirobin ttn-gateway[14121]: /opt/ttn-gateway/gateway-remote-config /opt/ttn-gateway/bin
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: Already up-to-date.
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: HEAD is now at f8ebd54 Merge pull request #89 from sirfragles/patch-2
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: /opt/ttn-gateway/bin
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: [TTN Gateway]: Use Gateway EUI B827EBFFFE9DDF94 based on eth0
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: *** Poly Packet Forwarder for Lora Gateway ***
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: Version: 2.1.0
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: *** Lora concentrator HAL library version info ***
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: Version: 3.1.0; Options: native;
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: ***
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: INFO: Little endian host
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: INFO: found global configuration file global_conf.json, parsing it
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: INFO: global_conf.json does contain a JSON object named SX1301_conf, parsing SX1301 parameters
Apr  6 15:19:33 raspirobin ttn-gateway[14121]: INFO: lorawan_public 1, clksrc 1
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Configuring TX LUT with 16 indexes
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: radio 0 enabled (type SX1257), center frequency 867500000, RSSI offset -166.000000, tx enabled 1
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: radio 1 enabled (type SX1257), center frequency 868500000, RSSI offset -166.000000, tx enabled 0
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 0>  radio 1, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 1>  radio 1, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 2>  radio 1, IF 0 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 3>  radio 0, IF -400000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 4>  radio 0, IF -200000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 5>  radio 0, IF 0 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 6>  radio 0, IF 200000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora multi-SF channel 7>  radio 0, IF 400000 Hz, 125 kHz bw, SF 7 to 12
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Lora std channel> radio 1, IF -200000 Hz, 250000 Hz bw, SF 7
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: FSK channel> radio 1, IF 300000 Hz, 125000 Hz bw, 50000 bps datarate
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: global_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: gateway MAC address is configured to AA555A0000000000
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Found 2 servers in array.
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Server 0 configured to "127.0.0.1", with port up "1680" and port down "1681"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Server 1 configured to "iot.semtech.com", with port up "1680" and port down "1680"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Found 5 system calls in array.
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: System command 0: "df -m"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: System command 1: "free -h"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: System command 2: "uptime"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: System command 3: "who -a"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: System command 4: "uname -a"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: monitor hostname or IP address is configured to "127.0.0.1"
Apr  6 15:19:34 raspirobin systemd[1]: ttn-gateway.service: main process exited, code=exited, status=1/FAILURE
Apr  6 15:19:34 raspirobin systemd[1]: Unit ttn-gateway.service entered failed state.
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: monitor port is configured to "2008"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: ghost hostname or IP address is configured to "127.0.0.1"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: ghost port is configured to "1918"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: downstream keep-alive interval is configured to 10 seconds
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: statistics display interval is configured to 30 seconds
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: upstream PUSH_DATA time-out is configured to 100 ms
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with a valid CRC will be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with a CRC error will NOT be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with no CRC will NOT be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: GPS serial port path is configured to "/dev/ttyAMA0"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: SSH path is configured to "/usr/bin/ssh"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: SSH port is configured to 22
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: HTTP port is configured to 80
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: NGROK path is configured to "/usr/bin/ngrok"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference latitude is configured to 10.000000 deg
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference longitude is configured to 20.000000 deg
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference altitude is configured to -1 meters
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: GPS is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Using fake GPS coordinates instead of real.
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Upstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Downstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Ghoststream data is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Radiostream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Statusstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Beacon is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Monitor is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Platform configured to "IMST + Rpi"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Contact email configured to "operator@gateway.tst"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Description configured to "Update me"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: found local configuration file local_conf.json, parsing it
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: redefined parameters will overwrite global parameters
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: local_conf.json does not contain a JSON object named SX1301_conf
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: local_conf.json does contain a JSON object named gateway_conf, parsing gateway parameters
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: gateway MAC address is configured to B827EBFFFE9DDF94
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Found 1 servers in array.
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Server 0 configured to "router.eu.thethings.network", with port up "1700" and port down "1700"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with a valid CRC will be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with a CRC error will NOT be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: packets received with no CRC will NOT be forwarded
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference latitude is configured to 50.812153 deg
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference longitude is configured to 3.085640 deg
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Reference altitude is configured to 40 meters
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: GPS is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Upstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Downstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Ghoststream data is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Radiostream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Statusstream data is enabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Beacon is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Monitor is disabled
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Contact email configured to "lora@rallypodium.be"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Description configured to "TTN Belgium - private"
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: Successfully contacted server router.eu.thethings.network
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: INFO: [main] Starting the concentrator
Apr  6 15:19:34 raspirobin ttn-gateway[14121]: ERROR: [main] failed to start the concentrator
```

I just followed the installation....

**Comment by gonzalocasas** [comment] 2017-04-06 13:42
Hi @Advil-Robin, the `failed to start the concentrator` error message usually means your power supply unit is not providing enough power. So try the following:
 - Make sure your PSU is rated at least 2A.
 - If it is already, try a different one.
 - If that doesn't work, then check the wiring, if you have jumper wires, then double and triple check, is very common to connect them wrong.
 - If you have a backplane, then make sure nothing is upside down or connected the wrong way.
 - Also, make sure you have enabled SPI in your raspberry pi (using `raspi-config`)

Let me know how it goes...

**Comment by Advil-Robin** [comment] 2017-04-06 13:45
Hi @gonzalocasas !

So I have an UPS board above my PI and on top of that, I have the Dragino LoRa/GPS module HAT.

So It's not possible the wires are wrong. I'm using the 2.5A power supply of the pi itself. SPI is enabled.

I'll try to get it working without the UPS under it, it might because of that.

**Comment by Advil-Robin** [comment] 2017-04-06 13:54
Update;
Even without the UPS it doesn't work.

**Comment by dylancollaud** [comment] 2017-04-06 13:58
Hi Robin,
Have you a green led "on" on the IC880A Board ?
On my board, on component were missing and the board did not start.

**Comment by gonzalocasas** [comment] 2017-04-06 13:59
@Advil-Robin: well, the problem is clear. You're not using the right board. You have a Dragino LoRa, not an IMST iC880a concentrator board.

**Comment by Advil-Robin** [comment] 2017-04-06 14:00
I had one, but since I tried this library i haven't.

So I've tried a different repo (don't know anymore wich one) and then I had a green LED. I used the exact same setup, but with this repo, it doesn't seem tp work...

@gonzalocasas wich repo should I use then to also connect to TTN?

**Comment by gonzalocasas** [comment] 2017-04-06 14:02
@Advil-Robin: so, do you have an iC880a board or not?

**Comment by Advil-Robin** [comment] 2017-04-06 14:04
@gonzalocasas No, I have not. It's a dragino HAT with LoRa on it.

But it's okay, I wanted to use it as a LoRa gateway, but it seems not possible?

**Comment by gonzalocasas** [comment] 2017-04-06 14:11
The dragino is mostly a end-device, not a gateway. It can be run as a gateway, but not a full one. The issue is that the dragino board only supports one channel at a time, and a LoRaWAN gateway needs multi-channel support to be compliant (otherwise you're nodes will receive 1 out of 8 packets).

You can still use the dragino for testing provided you make a few adjustments to your test nodes as well, but this repository doesn't really fit for that purpose, what you want is one of the single-channel gateway repositories around.

I will close this for now then.

**Closed** 2017-04-06 14:11 UTC
